name: deployment
on:
  push:
    # Only deploy upon new commits to `main`
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2.1.2
      - id: configure
        uses: actions/configure-pages@v5.0.0

      - run: bun install
      - run: bun run build
        env:
          BASE_URL: ${{ steps.configure.outputs.base_url }}

      - uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: dist/client
      - uses: actions/deploy-pages@v4.0.5
permissions:
  pages: write
  id-token: write
